openapi: 3.0.3
info:
    title: Wallet API
    description: Service for processing user balance transactions
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /health:
        get:
            tags:
                - wallet
            summary: healthcheck wallet
            description: Health check
            operationId: wallet#healthcheck
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HealthcheckResponseBody'
                            example:
                                status: Natus et quasi quod.
    /user/{userId}/balance:
        get:
            tags:
                - wallet
            summary: getBalance wallet
            description: Get user balance
            operationId: wallet#getBalance
            parameters:
                - name: userId
                  in: path
                  description: User ID
                  required: true
                  schema:
                    type: integer
                    description: User ID
                    example: 1
                    format: int64
                    minimum: 1
                  example: 1
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetBalanceOKResponseBody'
                            example:
                                balance: "9.25"
                                userId: 17231541303881807787
                "404":
                    description: Not Found response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetBalanceOKResponseBody'
                            example:
                                balance: "9.25"
                                userId: 13119423219798380334
                "500":
                    description: Internal Server Error response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetBalanceOKResponseBody'
                            example:
                                balance: "9.25"
                                userId: 9089563475417464449
    /user/{userId}/transaction:
        post:
            tags:
                - wallet
            summary: createTransaction wallet
            description: Process transaction for user
            operationId: wallet#createTransaction
            parameters:
                - name: userId
                  in: path
                  description: User ID
                  required: true
                  schema:
                    type: integer
                    description: User ID
                    example: 1
                    format: int64
                    minimum: 1
                  example: 1
                - name: Source-Type
                  in: header
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    example: game
                    enum:
                        - game
                        - server
                        - payment
                  example: game
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateTransactionRequestBody'
                        example:
                            amount: "10.15"
                            state: win
                            transactionId: tx-123
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                "409":
                    description: Conflict response.
                "500":
                    description: Internal Server Error response.
components:
    schemas:
        CreateTransactionRequestBody:
            type: object
            properties:
                amount:
                    type: string
                    example: "10.15"
                state:
                    type: string
                    example: win
                    enum:
                        - win
                        - lose
                transactionId:
                    type: string
                    example: tx-123
            example:
                amount: "10.15"
                state: win
                transactionId: tx-123
            required:
                - state
                - amount
                - transactionId
        GetBalanceOKResponseBody:
            type: object
            properties:
                balance:
                    type: string
                    example: "9.25"
                userId:
                    type: integer
                    example: 10956105879580666055
                    format: int64
            example:
                balance: "9.25"
                userId: 2646845335295583452
            required:
                - userId
                - balance
        HealthcheckResponseBody:
            type: object
            properties:
                status:
                    type: string
                    example: Quos rerum.
            example:
                status: Voluptas omnis.
            required:
                - status
tags:
    - name: wallet
      description: Wallet service
